### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by lparis**
@kozlovic @ColinSullivan1 Added links to API docs.
@mcqueary Is there a link to the JavaDoc for the Java client? Do you need help with this?

### CODE REVIEW

**Comment by kozlovic** [comment]
LGTM

**Comment by ColinSullivan1** [comment]
Likewise, LGTM.

**Comment by mcqueary** [comment]
The java client doc link is http://nats-io.github.io/jnats

**Comment by lparis** [comment]
@kozlovic @ColinSullivan1 @mcqueary -- Once more, added Javadoc link as well as instructions for generating docs for Go client and server using Godoc tool. Thanks.

**Comment by kozlovic** [comment]
Again, LGTM.

**Comment by mcqueary** [comment]
Minor nitpick, not even related to what you changed, but "built-in" should have a hyphen.

**Comment by lparis** [comment]
Added hyphen, merging

**Pull request merged**
